spring:
  datasource:
    url: jdbc:mysql://student-db:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true
    username: studentuser
    password: studentpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    com.assesment.studentservice: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
